- TVRename#/TheTVDB/Banner.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TheTVDB.cs
> Added a first cut of multi-lingual support

- TVRename#/Forms/UI.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TheTVDB.cs
https://groups.google.com/forum/#!topic/tvrename/IfYafWWs0y4
> Fixes issues raised by Jurgen

- TVRename#/DownloadIdentifers/DownloadFanartJPG.cs
- TVRename#/DownloadIdentifers/DownloadIdentifiersController.cs
- TVRename#/DownloadIdentifers/DownloadXBMCImages.cs
- TVRename#/DownloadIdentifers/DownloadXBMCMetaData.cs
- TVRename#/Exporter/Exporter.cs
- TVRename#/Exporter/MissingXML.cs
- TVRename#/Exporter/ShowsTXT.cs
- TVRename#/Forms/Preferences.Designer.cs
- TVRename#/Forms/Preferences.cs
- TVRename#/Forms/Preferences.resx
- TVRename#/Forms/UI.cs
- TVRename#/ItemsAndActions/ActionNFO.cs
- TVRename#/Settings/Settings.cs
- TVRename#/TVRename#.csproj
- TVRename#/TVRename/TVDoc.cs
- Export show names to txt file
- Split nfo files for series / episodes
- update XBMC to Kodi
> Added 2 newfeatures

- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TheTVDB.cs
https://groups.google.com/forum/#!topic/tvrename/IfYafWWs0y4
> Few updates based on feedback in this thread: 

- TVRename#/App/AutoFolderMonitor.cs
- TVRename#/Forms/UI.cs
- TVRename#/TVRename/TVDoc.cs
> Reverted some ill-considered changes

- TVRename#/Forms/UI.cs
https://github.com/jamoamo/tvrename/commit/f5f8c503225cd463291568a51b5e73504b1b5f67 on master to ease conflicts
> Mirror jamoamo change

- TVRename#/Exporter/Exporter.cs
- TVRename#/Exporter/MissingXML.cs
- TVRename#/Exporter/ShowsTXT.cs
- TVRename#/Exporter/UpcomingRSS.cs
- TVRename#/Exporter/UpcomingXML.cs
- TVRename#/Settings/Settings.cs
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/Banner.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TheTVDB.cs
> More logging additions

- TVRename#/Forms/UI.cs
- TVRename#/TVRename/TVDoc.cs
> Logging tidy up

- TVRename#/NLog.config
> Updated location of logs to be next to user files

- TVRename#/Forms/UI.cs
- TVRename#/TVRename#.csproj
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/TheTVDB.cs
- TVRename#/Utility/BT.cs
> Fix for #191 and logging updates to reduce AppVeyor noise

- TVRename#/App/CommandLineArgs.cs
- TVRename#/App/Program.cs
- TVRename#/Forms/UI.cs
> Fix for #180

- TVRename#/TheTVDB/TheTVDB.cs
This fixes the last two compiler warnings when building a release.
> Fix compiler warnings

- TVRename#.sln.DotSettings
- TVRename#/TVRename#.csproj.DotSettings
Update Resharper code style guidelines
> Style Guidelines

- TVRename#/Settings/Searchers.cs
This removes the dead links discussed in #232 and adds Google.
> Remove dead search engine links

- TVRename#/TheTVDB/TheTVDB.cs
Addition of logging and catching errors . The net was down on my machine and TVR crashed!
> Improved error handling around what we receive from TVDB

- TVRename#/TheTVDB/TheTVDB.cs
Add (readd) function to automatically upgrade a series that is 10% dirty to be 100% dirty and update all episodes
> Dirty upgrade

- TVRename#.sln.DotSettings
- TVRename#/App/CommandLineArgs.cs
- TVRename#/NLog.config
- TVRename#/TVRename#.csproj.DotSettings
- TVRename#/app.config
- TVRename#/packages.config
Basic cleanup for metadata files
> Metadata File Cleanup

- TVRename#/Forms/UI.cs
> Rename settings to preferences

- TVRename#/App/AutoFolderMonitor.cs
- TVRename#/Forms/UI.cs
This cleans up and documents the auto folder monitor, no logic or breaking changes.
> Cleanup auto folder monitor

- Installer.nsi
This updates the installer to use v3 paths and remove v2 before install.
This pull request is a replacement for #203, refactored to include #238.
> v3 Installer

- _layouts/default.html
Tweaked downloads button link, now points to:
https://github.com/TV-Rename/tvrename/releases
> updated downloads link

- TVRename#/NLog.config
> Improved logging of exceptions

- TVRename#/Forms/UpdateNotification.Designer.cs
- TVRename#/Forms/UpdateNotification.cs
> Enhancements to Update to show Markup

- TVRename#/Forms/UpdateNotification.cs
- TVRename#/TVRename/TVDoc.cs
> Bug fix to address #299

- index.md
> Minor tweaks spotted this morning

- TVRename#/TVRename/TVDoc.cs
- TVRename#/Utility/Helpers.cs
> Bug Fixes (#18)

- TVRename.Core/Actions/KodiEpisodeAction.cs
- TVRename.Core/Actions/KodiShowAction.cs
- TVRename.Core/Extensions/XmlExtensions.cs
- TVRename.Core/Metadata/Identifiers/KodiIdentifier.cs
- TVRename.Core/Models/Cache/Episode.cs
- TVRename.Core/Models/ProcessedEpisode.cs
- TVRename.Core/Models/ProcessedShow.cs
- TVRename.Core/TVRename.Core.csproj
Feel free to pick parts/discard  - just wanted to put forward some solutions to issues in #326 rather than throw in problems!
> Possible changes for #326

- TVRename#/App/ApplicationBase.cs
- TVRename#/DownloadIdentifers/IncorrectFileDates.cs
- TVRename#/Finders/FileFinder.cs
- TVRename#/Finders/SABnzbdFinder.cs
- TVRename#/Finders/uTorrentFinder.cs
- TVRename#/Forms/BugReport.cs
- TVRename#/Forms/CustomNameDesigner.cs
- TVRename#/Forms/TVRenameSplash.cs
- TVRename#/Forms/UI.Designer.cs
- TVRename#/Forms/UI.cs
- TVRename#/Forms/UpdateNotification.Designer.cs
- TVRename#/Forms/UpdateNotification.cs
- TVRename#/ItemsAndActions/ActionItem.cs
- TVRename#/Properties/Resources.Designer.cs
- TVRename#/Settings/Settings.cs
- TVRename#/Settings/ShowsAndEpisodes.cs
- TVRename#/TVRename#.csproj
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/Utility/Helpers.cs
- TVRename#/app.config
#335 
#337 
#339 
#18  (part complete)
#309 (revert as it caused problems)
#345 
From Forums:
* DVD Ordering
* Delete source folder
> Many Updates

- TVRename#/App/ApplicationBase.cs
- TVRename#/App/CommandLineArgs.cs
- TVRename#/App/Program.cs
- TVRename#/DownloadIdentifers/DownloadXBMCImages.cs
- TVRename#/Forms/AddEditShow.cs
- TVRename#/Forms/CustomNameDesigner.cs
- TVRename#/Forms/UI.cs
- TVRename#/Ipc/IRemoteActions.cs
- TVRename#/Ipc/RemoteClient.cs
- TVRename#/ItemsAndActions/ActionNFO.cs
- TVRename#/Settings/CustomName.cs
- TVRename#/Settings/ShowsAndEpisodes.cs
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/Season.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TheTVDB.cs
- TVRename#/Utility/Sorters.cs
#337 
#343 
#344 
#347 
* New Feature:  Added /quickscan and /recentscan as well as /? to the CLI Version
> Updates for 2.4

- TVRename#/App/Program.cs
- TVRename#/Forms/UI.cs
- TVRename#/TheTVDB/TheTVDB.cs
> Bug fixes for RC3

- TVRename#/App/ApplicationBase.cs
- TVRename#/App/CommandLineArgs.cs
- TVRename#/App/Program.cs
- TVRename#/ItemsAndActions/ActionDateTouch.cs
- TVRename#/TVRename/TVDoc.cs
- TVRename#/Utility/Helpers.cs
Fixes for:
* Command line handling improved
* Name Change for 'File Touch'
* Fix for #381 - Crashes on Auto Folder Create
> Incremental update - 3x bug fix

- TVRename#/Forms/Preferences.Designer.cs
- TVRename#/Forms/Preferences.cs
- TVRename#/Forms/UI.cs
- TVRename#/Settings/Settings.cs
- TVRename#/Settings/ShowsAndEpisodes.cs
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/Episode.cs
- TVRename#/TheTVDB/TheTVDB.cs
- TVRename#/Utility/Helpers.cs
> Update from latest

- TVRename#/Exporter/ShowsHTML.cs
> Slight update to HTML formatting

- TVRename#/TVRename#.csproj
- TVRename#/TheTVDB/TheTVDB.cs
- TVRename#/TheTVDB/TvDbTokenProvider.cs
Refactored tvdb token to provider, fixed comparison from previous commit, fixed some code-styling issues
> Fix for #421 - resubmitted with fixes

- TVRename#.sln.DotSettings
- TVRename#/Exporter/ShowsHTML.cs
- TVRename#/Exporter/UpcomingRSS.cs
- TVRename#/Finders/FileFinder.cs
- TVRename#/Finders/uTorrentFinder.cs
- TVRename#/Forms/CustomNameDesigner.cs
- TVRename#/Forms/EditRules.cs
- TVRename#/Forms/FolderBrowserDialogEx.cs
- TVRename#/Forms/FolderMonitor.Designer.cs
- TVRename#/Forms/FolderMonitor.cs
- TVRename#/Forms/FolderMonitor.resx
- TVRename#/Forms/UI.Designer.cs
- TVRename#/Forms/UI.cs
- TVRename#/Forms/UpcomingPopup.cs
- TVRename#/ItemsAndActions/ActionCopyMoveRename.cs
- TVRename#/ItemsAndActions/ActionDelete.cs
- TVRename#/ItemsAndActions/ActionItem.cs
- TVRename#/ItemsAndActions/ActionMede8erViewXML.cs
- TVRename#/ItemsAndActions/ActionMede8erXML.cs
- TVRename#/ItemsAndActions/ActionNFO.cs
- TVRename#/ItemsAndActions/ActionPyTivoMeta.cs
- TVRename#/ItemsAndActions/ItemSABnzbd.cs
- TVRename#/ItemsAndActions/ItemuTorrenting.cs
- TVRename#/Settings/CustomName.cs
- TVRename#/TVRename#.csproj
- TVRename#/TVRename/ActionEngine.cs
- TVRename#/TVRename/TVDoc.cs
- TVRename#/TheTVDB/SeriesInfo.cs
- TVRename#/TheTVDB/TvDbTokenProvider.cs
> Fix for #419

- TVRename#/ItemsAndActions/ActionNFO.cs
> Code Tidy Up

- TVRename/packages.config
> Update to 4.6.2

- TVRename/DownloadIdentifers/DownloadXBMCImages.cs
- TVRename/Forms/Preferences.Designer.cs
- TVRename/Forms/Preferences.cs
- TVRename/Settings/Settings.cs
> Remove eden

- TVRename/DownloadIdentifers/DownloadXBMCImages.cs
- TVRename/Forms/Preferences.Designer.cs
- TVRename/Forms/Preferences.cs
- TVRename/Settings/Settings.cs
> Removed Eden Support

- TVRename/Forms/UI.Designer.cs
Sunday is not the fist day of the week everywhere.
> let user locale determine the first day of the week

- TVRename/Forms/Preferences/Preferences.Designer.cs
- TVRename/Forms/Preferences/Preferences.cs
- TVRename/Forms/UI.cs
- TVRename/Settings/Settings.cs
Tired to aswer no each time i delete a show from a show list
>  Preference option to enable file deleting when deleting show 
